# GlucoSense Obliterator v1
### Diabetes Risk Classification — Production-Grade ML Pipeline

**Datasets:**
- `diabetes_prediction_dataset.csv` — 100K rows · HbA1c, blood_glucose, BMI, smoking, age
- `diabetes.csv` — PIMA Indians · 768 rows · classic benchmark

**CRITICAL DISCLAIMER — Read before running:**
Features `HbA1c_level` and `blood_glucose_level` are the WHO/ADA clinical diagnostic criteria.
The model learns these thresholds — that is expected for lab-based data.
For antenna-based sensing, these features will NOT exist. Different model required.

**Note on R² / Adjusted R²:**
These are regression metrics (predicting a continuous value like exact glucose mg/dL).
This notebook solves a CLASSIFICATION problem (diabetic vs not).
R² does NOT apply here. The correct metrics are: Accuracy, AUC, F1, MCC, PR-AUC.
R²/Adjusted-R² become relevant ONLY in the antenna regression notebook (predicting BGL value).

In [1]:
# ── 0. Imports ─────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # non-interactive backend for script execution
import seaborn as sns
import warnings, os, pickle
warnings.filterwarnings('ignore')

from IPython.display import display

from sklearn.model_selection import (
    StratifiedKFold, cross_val_score, train_test_split, learning_curve
)
from sklearn.preprocessing import LabelEncoder, RobustScaler
from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score, precision_score, recall_score,
    average_precision_score, classification_report, confusion_matrix,
    ConfusionMatrixDisplay, RocCurveDisplay, PrecisionRecallDisplay,
    precision_recall_curve, brier_score_loss,
    matthews_corrcoef, balanced_accuracy_score, cohen_kappa_score
)
from imblearn.over_sampling import SMOTE

from catboost import CatBoostClassifier
from xgboost import XGBClassifier
import lightgbm as lgb
import shap
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

SEED = 42
CV_N = 5
np.random.seed(SEED)
SAVE_DIR = '.'
print('All imports OK.')
print(f'Python: {__import__("sys").version.split()[0]}')
import catboost, xgboost, lightgbm, sklearn
print(f'CatBoost {catboost.__version__}  XGBoost {xgboost.__version__}  '
      f'LightGBM {lightgbm.__version__}  sklearn {sklearn.__version__}')

All imports OK.
Python: 3.13.5
CatBoost 1.2.10  XGBoost 3.1.2  LightGBM 4.6.0  sklearn 1.8.0

In [2]:
# ── 1. Load ────────────────────────────────────────────────────────────────
df_main = pd.read_csv('diabetes_prediction_dataset.csv')
df_pima = pd.read_csv('diabetes.csv')
print(f'PRIMARY  {df_main.shape}  cols: {df_main.columns.tolist()}')
print(f'PIMA     {df_pima.shape}  cols: {df_pima.columns.tolist()}')
print()
display(df_main.describe())
display(df_pima.describe())

PRIMARY  (100000, 9)  cols: ['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes']
PIMA     (768, 9)  cols: ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [3]:
# ── 2. Data Integrity Audit ─────────────────────────────────────────────────
def full_audit(df, name, target):
    print(f'\n{"="*62}\nAUDIT: {name}\n{"="*62}')
    print(f'Shape:           {df.shape}')

    dupes = df.duplicated().sum()
    print(f'Duplicates:      {dupes}  ({dupes/len(df)*100:.2f}%)')

    nulls = df.isnull().sum()
    print(f'Nulls:\n{nulls[nulls>0] if nulls.sum()>0 else "  None"}')

    num_cols = df.select_dtypes(include=[np.number]).columns.drop(target, errors='ignore')
    binary_cols = [c for c in num_cols if df[c].nunique() <= 4]
    cont_cols   = [c for c in num_cols if c not in binary_cols]

    zeros = {c: int((df[c]==0).sum()) for c in cont_cols if (df[c]==0).sum()>0}
    if zeros:
        print(f'Impossible zeros in continuous cols:')
        for c,n in zeros.items(): print(f'  {c}: {n} ({n/len(df)*100:.1f}%)')

    print(f'Outliers |z|>4:')
    found_outliers = False
    for c in cont_cols:
        z = np.abs((df[c] - df[c].mean()) / (df[c].std()+1e-9))
        n = int((z>4).sum())
        if n>0:
            print(f'  {c}: {n} (max={df[c].max():.1f}, min={df[c].min():.1f})')
            found_outliers = True
    if not found_outliers: print('  None')

    vc = df[target].value_counts()
    minority_pct = vc.min()/len(df)*100
    print(f'Target "{target}":\n{vc}')
    if minority_pct < 20:
        print(f'  WARNING: Imbalanced — minority={minority_pct:.1f}% → use class_weight + F1/PR-AUC')

full_audit(df_main, 'diabetes_prediction_dataset', 'diabetes')
full_audit(df_pima, 'PIMA Indians', 'Outcome')

==============================================================
AUDIT: diabetes_prediction_dataset
==============================================================
Shape:           (100000, 9)
Duplicates:      3854  (3.85%)
Nulls:
  None
Outliers |z|>4:
  bmi: 383 (max=95.7, min=10.0)
Target "diabetes":
diabetes
0    91500
1     8500
Name: count, dtype: int64
  WARNING: Imbalanced — minority=8.5% → use class_weight + F1/PR-AUC

==============================================================
AUDIT: PIMA Indians
==============================================================
Shape:           (768, 9)
Duplicates:      0  (0.00%)
Nulls:
  None
Impossible zeros in continuous cols:
  Pregnancies: 111 (14.5%)
  Glucose: 5 (0.7%)
  BloodPressure: 35 (4.6%)
  SkinThickness: 227 (29.6%)
  Insulin: 374 (48.7%)
  BMI: 11 (1.4%)
Outliers |z|>4:
  SkinThickness: 1 (max=99.0, min=0.0)
  Insulin: 7 (max=846.0, min=0.0)
  BMI: 12 (max=67.1, min=0.0)
  DiabetesPedigreeFunction: 5 (max=2.4, min=0.1)
  Age: 1 (max=81.0, min=21.0)
Target "Outcome":
Outcome
0    500
1    268
Name: count, dtype: int64

In [4]:
# ── 3. Clean PRIMARY ────────────────────────────────────────────────────────
df = df_main.copy()

before = len(df)
df = df.drop_duplicates()
print(f'Dropped {before-len(df)} duplicates. Remaining: {len(df)}')

# Drop leak columns
leak = [c for c in df.columns if c.lower() in ['unnamed: 0','unnamed:0','index','id','patient_id']]
if leak: df = df.drop(columns=leak); print(f'Dropped leak cols: {leak}')

# Domain-based outlier CAPPING (clinical thresholds from literature)
# HbA1c: normal 4-6%, diabetic >6.5%, physiologically impossible >20%
# blood_glucose: normal 70-99 mg/dL fasting, DKA >600 = ER emergency
# BMI: <10 = measurement error, >70 = extreme but physiologically possible
# age: must be positive, max realistic ~120
caps = {'HbA1c_level': (3.5,14.0), 'blood_glucose_level': (50,600), 'bmi': (10,70), 'age': (1,110)}
for col, (lo,hi) in caps.items():
    if col in df.columns:
        n = int(((df[col]<lo)|(df[col]>hi)).sum())
        df[col] = df[col].clip(lo,hi)
        print(f'  Clipped {col} to [{lo},{hi}]: {n} values')

# Encode categoricals
le_map = {}
for col in df.select_dtypes(include=['object']).columns:
    if col == 'diabetes': continue
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    le_map[col] = le

print(f'\nFinal shape: {df.shape}  Nulls: {df.isnull().sum().sum()}')
display(df.describe())

Dropped 3854 duplicates. Remaining: 96146
  Clipped HbA1c_level to [3.5,14.0]: 0 values
  Clipped blood_glucose_level to [50,600]: 0 values
  Clipped bmi to [10,70]: 19 values
  Clipped age to [1,110]: 910 values

Final shape: (96146, 9)  Nulls: 0

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
count,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000,96146.000000
mean,0.416065,41.798798,0.077601,0.040803,2.231159,27.319263,5.532609,138.218231,0.088220
std,0.493287,22.454764,0.267544,0.197833,1.879963,6.751012,1.073232,40.909771,0.283616
min,0.000000,1.000000,0.000000,0.000000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,0.000000,24.000000,0.000000,0.000000,0.000000,23.400000,4.800000,100.000000,0.000000
50%,0.000000,43.000000,0.000000,0.000000,3.000000,27.320000,5.800000,140.000000,0.000000
75%,1.000000,59.000000,0.000000,0.000000,4.000000,29.860000,6.200000,159.000000,0.000000
max,2.000000,80.000000,1.000000,1.000000,5.000000,70.000000,9.000000,300.000000,1.000000

In [5]:
# ── 4. Clean PIMA (zeros = missing values) ──────────────────────────────────
df_p = df_pima.copy()
# PIMA specific: Glucose, BloodPressure, SkinThickness, Insulin, BMI = 0 is impossible
pima_zero_na = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
for col in pima_zero_na:
    n = int((df_p[col]==0).sum())
    df_p[col] = df_p[col].replace(0, np.nan)
    print(f'  PIMA {col}: {n} zeros → NaN')

feat_p = [c for c in df_p.columns if c!='Outcome']
knn_imp = KNNImputer(n_neighbors=5, weights='distance')
df_p[feat_p] = knn_imp.fit_transform(df_p[feat_p])
print(f'KNN imputed. Nulls after: {df_p.isnull().sum().sum()}')
print(f'PIMA shape: {df_p.shape}')

  PIMA Glucose: 5 zeros → NaN
  PIMA BloodPressure: 35 zeros → NaN
  PIMA SkinThickness: 227 zeros → NaN
  PIMA Insulin: 374 zeros → NaN
  PIMA BMI: 11 zeros → NaN
KNN imputed. Nulls after: 0
PIMA shape: (768, 9)

In [6]:
# ── 5. Target leakage analysis ─────────────────────────────────────────────
print('=== TARGET LEAKAGE ANALYSIS ===')
print('HbA1c>=6.5 and blood_glucose>=126 are WHO/ADA diagnostic criteria.')
print('If these features alone predict the label well, the model is partly learning thresholds.')
print('That is valid for lab-based classification. Document this in any paper.')
print()
from sklearn.metrics import accuracy_score as acc_s
pred_hb  = (df['HbA1c_level']>=6.5).astype(int)
pred_gl  = (df['blood_glucose_level']>=126).astype(int)
pred_and = ((df['HbA1c_level']>=6.5) & (df['blood_glucose_level']>=126)).astype(int)
print(f'HbA1c>=6.5 alone:              Acc={acc_s(df["diabetes"],pred_hb):.4f}')
print(f'glucose>=126 alone:            Acc={acc_s(df["diabetes"],pred_gl):.4f}')
print(f'HbA1c>=6.5 AND glucose>=126:   Acc={acc_s(df["diabetes"],pred_and):.4f}')
print()
# Baseline: predict majority class (no diabetes)
majority_acc = 1 - df['diabetes'].mean()
print(f'Naive baseline (always predict 0): Acc={majority_acc:.4f}')
print('A good model must beat this baseline significantly.')

=== TARGET LEAKAGE ANALYSIS ===
HbA1c>=6.5 and blood_glucose>=126 are WHO/ADA diagnostic criteria.
If these features alone predict the label well, the model is partly learning thresholds.
That is valid for lab-based classification. Document this in any paper.

HbA1c>=6.5 alone:              Acc=0.8104
glucose>=126 alone:            Acc=0.3692
HbA1c>=6.5 AND glucose>=126:   Acc=0.8588

Naive baseline (always predict 0): Acc=0.9118
A good model must beat this baseline significantly.

In [7]:
# ── 6. EDA ─────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(2,4,figsize=(20,9))
fig.suptitle('Feature Distributions by Diabetes Status', fontsize=13, fontweight='bold')
for i,col in enumerate(['age','bmi','HbA1c_level','blood_glucose_level']):
    ax = axes[0][i]
    df[df['diabetes']==0][col].hist(ax=ax,bins=40,alpha=0.6,color='#083D77',label='No DM',density=True)
    df[df['diabetes']==1][col].hist(ax=ax,bins=40,alpha=0.6,color='#DA4167',label='DM',density=True)
    ax.set_title(col,fontweight='bold'); ax.legend(fontsize=8)
for i,col in enumerate(['gender','hypertension','heart_disease','smoking_history']):
    ax = axes[1][i]
    df.groupby(col)['diabetes'].mean().plot(kind='bar',ax=ax,color='#083D77',rot=30)
    ax.set_title(f'DM rate by {col}',fontweight='bold'); ax.set_ylabel('Rate')
plt.tight_layout(); plt.savefig('eda_distributions.png',dpi=100,bbox_inches='tight'); plt.close()
print('Saved: eda_distributions.png')

# Correlation matrix
fig,ax = plt.subplots(figsize=(10,8))
sns.heatmap(df.select_dtypes(include=[np.number]).corr(), annot=True, fmt='.2f', cmap='Blues', center=0, ax=ax)
ax.set_title('Feature Correlations', fontweight='bold')
plt.tight_layout(); plt.savefig('correlation_matrix.png',dpi=100,bbox_inches='tight'); plt.close()
print('Saved: correlation_matrix.png')
print('\nCorrelation with target:')
print(df.corr(numeric_only=True)['diabetes'].sort_values(ascending=False).to_string())

Saved: eda_distributions.png
Saved: correlation_matrix.png

Correlation with target:
diabetes               1.000000
blood_glucose_level    0.424336
HbA1c_level            0.406408
age                    0.264962
bmi                    0.215246
hypertension           0.195710
heart_disease          0.170711
smoking_history        0.088471
gender                 0.037613

In [8]:
# ── 7. Split + Scale + Feature Engineering (CORRECT ORDER) ─────────────────
# FIX for critical bug: binary threshold features must be computed from RAW data,
# not from scaled data. RobustScaler changes the units — threshold 6.5 in scaled
# space = HbA1c >= 14.90 in original units, which is almost never true.
# SOLUTION: split -> compute binary on raw -> scale continuous -> combine.

X_raw = df.drop(columns=['diabetes'])
y     = df['diabetes']

# Step 1: Split
X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X_raw, y, test_size=0.2, random_state=SEED, stratify=y
)

# Step 2: Binary features from RAW data (correct clinical thresholds)
def binary_features(X):
    """Compute binary flags from original-unit values only."""
    out = pd.DataFrame(index=X.index)
    if 'HbA1c_level' in X.columns:
        out['HbA1c_diabetic']    = (X['HbA1c_level'] >= 6.5).astype(int)     # WHO threshold
        out['HbA1c_prediabetic'] = ((X['HbA1c_level'] >= 5.7) & (X['HbA1c_level'] < 6.5)).astype(int)
    if 'blood_glucose_level' in X.columns:
        out['glucose_diabetic']  = (X['blood_glucose_level'] >= 126).astype(int)  # fasting threshold
        out['glucose_very_high'] = (X['blood_glucose_level'] >= 200).astype(int)
    if 'HbA1c_level' in X.columns and 'blood_glucose_level' in X.columns:
        out['dual_positive']     = (out['HbA1c_diabetic'] & out['glucose_diabetic']).astype(int)
    if 'bmi' in X.columns:
        out['bmi_obese']          = (X['bmi'] >= 30).astype(int)
        out['bmi_severely_obese'] = (X['bmi'] >= 35).astype(int)
    if 'age' in X.columns:
        out['age_senior']  = (X['age'] >= 45).astype(int)
        out['age_elderly'] = (X['age'] >= 60).astype(int)
    if 'hypertension' in X.columns and 'bmi' in X.columns:
        out['hyp_x_obese'] = X['hypertension'].values * out['bmi_obese'].values
    return out

bin_train = binary_features(X_train_raw)
bin_test  = binary_features(X_test_raw)

# Step 3: Scale CONTINUOUS features (fit only on train)
scaler = RobustScaler()
X_train_sc = pd.DataFrame(
    scaler.fit_transform(X_train_raw), columns=X_raw.columns, index=X_train_raw.index
)
X_test_sc  = pd.DataFrame(
    scaler.transform(X_test_raw), columns=X_raw.columns, index=X_test_raw.index
)

# Step 4: Add scaled interaction (makes sense in scaled space: relative magnitudes)
X_train_sc['HbA1c_x_glucose'] = X_train_sc['HbA1c_level'] * X_train_sc['blood_glucose_level']
X_test_sc['HbA1c_x_glucose']  = X_test_sc['HbA1c_level']  * X_test_sc['blood_glucose_level']

# Step 5: Combine scaled continuous + correct binary features
X_train = pd.concat([X_train_sc.reset_index(drop=True), bin_train.reset_index(drop=True)], axis=1)
X_test  = pd.concat([X_test_sc.reset_index(drop=True),  bin_test.reset_index(drop=True)],  axis=1)
y_train = y_train.reset_index(drop=True)
y_test  = y_test.reset_index(drop=True)

print(f'Train: {X_train.shape}  Test: {X_test.shape}')
print(f'Train +rate: {y_train.mean():.4f}  Test +rate: {y_test.mean():.4f}')
print(f'New features: {bin_train.columns.tolist()}')

# Verify fix: HbA1c_diabetic should flag a sensible proportion
print(f'\nHbA1c_diabetic flags: {X_train["HbA1c_diabetic"].sum()} rows '
      f'({X_train["HbA1c_diabetic"].mean()*100:.1f}%)')
print('(Should be ~16-20% of train, matching raw data HbA1c>=6.5 prevalence)')

Train: (76916, 19)  Test: (19230, 19)
Train +rate: 0.0882  Test +rate: 0.0882
New features: ['HbA1c_diabetic', 'HbA1c_prediabetic', 'glucose_diabetic', 'glucose_very_high', 'dual_positive', 'bmi_obese', 'bmi_severely_obese', 'age_senior', 'age_elderly', 'hyp_x_obese']

HbA1c_diabetic flags: 16053 rows (20.9%)
(Should be ~16-20% of train, matching raw data HbA1c>=6.5 prevalence)

In [9]:
# ── 8. Class imbalance: SMOTE on train ONLY ─────────────────────────────────
print(f'Before SMOTE: {y_train.value_counts().to_dict()}')
smote = SMOTE(random_state=SEED, k_neighbors=5)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)
print(f'After  SMOTE: {pd.Series(y_train_sm).value_counts().to_dict()}')
scale_pos = float((y_train==0).sum()) / float((y_train==1).sum())
print(f'scale_pos_weight for XGBoost: {scale_pos:.2f}')

Before SMOTE: {0: 70130, 1: 6786}

After  SMOTE: {0: 70130, 1: 70130}
scale_pos_weight for XGBoost: 10.33

In [10]:
# ── 9. Evaluation function — ALL metrics ───────────────────────────────────
# R² / Adjusted R² apply to REGRESSION tasks only.
# For classification, use: Accuracy, AUC, PR-AUC, F1, MCC, Balanced Accuracy,
# Specificity, Cohen's Kappa, Brier Score.
# MCC is the most robust single metric for imbalanced binary classification.

def evaluate(model, X_te, y_te, name, threshold=0.5):
    proba = model.predict_proba(X_te)[:, 1]
    pred  = (proba >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_te, pred).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    return {
        'Model':            name,
        'Threshold':        round(threshold, 3),
        'Accuracy':         round(accuracy_score(y_te, pred), 4),
        'Balanced_Acc':     round(balanced_accuracy_score(y_te, pred), 4),
        'AUC_ROC':          round(roc_auc_score(y_te, proba), 4),
        'PR_AUC':           round(average_precision_score(y_te, proba), 4),
        'F1':               round(f1_score(y_te, pred), 4),
        'Precision':        round(precision_score(y_te, pred, zero_division=0), 4),
        'Recall_Sensitivity': round(recall_score(y_te, pred, zero_division=0), 4),
        'Specificity':      round(specificity, 4),
        'MCC':              round(matthews_corrcoef(y_te, pred), 4),  # best single metric for imbalance
        'Kappa':            round(cohen_kappa_score(y_te, pred), 4),
        'Brier':            round(brier_score_loss(y_te, proba), 4),  # calibration (lower=better)
    }

print('Evaluation function ready. Metrics: Accuracy, Balanced_Acc, AUC_ROC, PR_AUC, F1,')
print('Precision, Recall/Sensitivity, Specificity, MCC (best for imbalance), Kappa, Brier.')
print()
print('Note: R² and Adjusted R² are NOT included — they are regression metrics.')
print('For antenna BGL regression, a separate notebook will report R²/Adjusted-R².')

Evaluation function ready. Metrics: Accuracy, Balanced_Acc, AUC_ROC, PR_AUC, F1,
Precision, Recall/Sensitivity, Specificity, MCC (best for imbalance), Kappa, Brier.

Note: R² and Adjusted R² are NOT included — they are regression metrics.
For antenna BGL regression, a separate notebook will report R²/Adjusted-R².

In [11]:
# ── 10. Baseline 5-fold CV ─────────────────────────────────────────────────
cv = StratifiedKFold(n_splits=CV_N, shuffle=True, random_state=SEED)

baselines = {
    'Logistic Regression': LogisticRegression(max_iter=2000, class_weight='balanced', random_state=SEED),
    'Random Forest':       RandomForestClassifier(n_estimators=300, class_weight='balanced', n_jobs=-1, random_state=SEED),
    'XGBoost':             XGBClassifier(n_estimators=500, learning_rate=0.05, max_depth=6,
                                          scale_pos_weight=scale_pos, eval_metric='logloss',
                                          n_jobs=-1, random_state=SEED, verbosity=0),
    'LightGBM':            lgb.LGBMClassifier(n_estimators=500, learning_rate=0.05, num_leaves=63,
                                               class_weight='balanced', n_jobs=-1, random_state=SEED, verbose=-1),
    'CatBoost':            CatBoostClassifier(iterations=1000, learning_rate=0.05, depth=6,
                                               auto_class_weights='Balanced', verbose=0, random_state=SEED),
}

print(f'{"Model":<25} {"CV Acc":>10} {"CV AUC":>10} {"CV F1":>10} {"CV PR-AUC":>12} {"CV MCC":>9}')
print('-'*80)
baseline_results = {}
for name, model in baselines.items():
    Xc, yc = (X_train_sm, y_train_sm) if name in ['Logistic Regression','Random Forest'] else (X_train, y_train)
    scores = {}
    for metric in ['accuracy','roc_auc','f1','average_precision','matthews_corrcoef']:
        sc = cross_val_score(model, Xc, yc, cv=cv, scoring=metric, n_jobs=-1)
        scores[metric] = sc
    baseline_results[name] = scores
    print(f'{name:<25} {scores["accuracy"].mean():.4f}±{scores["accuracy"].std():.3f} '
          f'{scores["roc_auc"].mean():.4f}±{scores["roc_auc"].std():.3f} '
          f'{scores["f1"].mean():.4f}±{scores["f1"].std():.3f} '
          f'{scores["average_precision"].mean():.4f}±{scores["average_precision"].std():.3f} '
          f'{scores["matthews_corrcoef"].mean():.4f}±{scores["matthews_corrcoef"].std():.3f}')

Model                         CV Acc     CV AUC      CV F1    CV PR-AUC    CV MCC
--------------------------------------------------------------------------------

Logistic Regression       0.8965±0.002 0.9689±0.001 0.8987±0.002 0.9687±0.001 0.7937±0.004

Random Forest             0.9801±0.001 0.9982±0.000 0.9801±0.001 0.9983±0.000 0.9603±0.001

XGBoost                   0.9175±0.001 0.9772±0.001 0.6554±0.004 0.8811±0.005 0.6410±0.005

LightGBM                  0.9394±0.001 0.9742±0.001 0.7047±0.005 0.8698±0.004 0.6800±0.004

CatBoost                  0.9207±0.001 0.9773±0.001 0.6630±0.004 0.8815±0.005 0.6473±0.005

In [12]:
# ── 11. McFadden pseudo-R² (classification analog of R²) ───────────────────
# McFadden's R² = 1 - (log-likelihood_full / log-likelihood_null)
# Only meaningful for logistic regression. Not for tree models.
# For tree models, use MCC instead — it is more informative.
print('=== McFadden pseudo-R² (Logistic Regression only) ===')
print('For tree models (CatBoost, XGBoost, etc.), use MCC as the primary quality metric.')
lr_full = LogisticRegression(max_iter=2000, class_weight='balanced', random_state=SEED)
lr_full.fit(X_train_sm, y_train_sm)
from sklearn.metrics import log_loss
ll_full = -log_loss(y_test, lr_full.predict_proba(X_test), normalize=False)
ll_null = -log_loss(y_test, np.full(len(y_test), y_train.mean()), normalize=False)
mcfadden_r2 = 1 - (ll_full / ll_null)
print(f'McFadden R²:          {mcfadden_r2:.4f}')
print(f'Interpretation: 0=no fit, 0.2=acceptable, 0.4=excellent, 1=perfect')
print(f'(Compare: actual R²/Adjusted-R² are for regression — not used in this notebook)')

=== McFadden pseudo-R² (Logistic Regression only) ===
For tree models (CatBoost, XGBoost, etc.), use MCC as the primary quality metric.

McFadden R²:          0.1967
Interpretation: 0=no fit, 0.2=acceptable, 0.4=excellent, 1=perfect
(Compare: actual R²/Adjusted-R² are for regression — not used in this notebook)

In [13]:
# ── 12. Optuna: CatBoost — optimize F1 ────────────────────────────────────
def catboost_obj(trial):
    p = {
        'iterations':          trial.suggest_int('iterations', 500, 3000),
        'learning_rate':       trial.suggest_float('learning_rate', 0.005, 0.15, log=True),
        'depth':               trial.suggest_int('depth', 4, 10),
        'l2_leaf_reg':         trial.suggest_float('l2_leaf_reg', 0.5, 10.0),
        'border_count':        trial.suggest_int('border_count', 64, 255),
        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 1.0),
        'random_strength':     trial.suggest_float('random_strength', 1e-3, 10.0, log=True),
        'grow_policy':         trial.suggest_categorical('grow_policy', ['SymmetricTree','Depthwise','Lossguide']),
        'auto_class_weights': 'Balanced', 'verbose': 0, 'random_state': SEED,
    }
    sc = cross_val_score(CatBoostClassifier(**p), X_train, y_train,
                          cv=StratifiedKFold(3,shuffle=True,random_state=SEED), scoring='f1', n_jobs=1)
    return sc.mean()

print('Tuning CatBoost: 50 trials, optimize F1 (correct for imbalanced data)...')
study_cb = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=SEED))
study_cb.optimize(catboost_obj, n_trials=50, show_progress_bar=True)
print(f'Best CatBoost F1: {study_cb.best_value:.4f}')

Tuning CatBoost: 50 trials, optimize F1 (correct for imbalanced data)...

  0%|          | 0/50 [00:00<?, ?it/s]

Best CatBoost F1: 0.7614

In [14]:
# ── 13. Optuna: XGBoost ────────────────────────────────────────────────────
def xgb_obj(trial):
    p = {
        'n_estimators':     trial.suggest_int('n_estimators', 300, 2500),
        'learning_rate':    trial.suggest_float('learning_rate', 0.005, 0.15, log=True),
        'max_depth':        trial.suggest_int('max_depth', 3, 10),
        'subsample':        trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma':            trial.suggest_float('gamma', 0.0, 2.0),
        'reg_alpha':        trial.suggest_float('reg_alpha', 0.0, 3.0),
        'reg_lambda':       trial.suggest_float('reg_lambda', 0.5, 5.0),
        'scale_pos_weight': scale_pos,
        'eval_metric': 'logloss', 'n_jobs': -1, 'random_state': SEED, 'verbosity': 0,
    }
    sc = cross_val_score(XGBClassifier(**p), X_train, y_train,
                          cv=StratifiedKFold(3,shuffle=True,random_state=SEED), scoring='f1', n_jobs=1)
    return sc.mean()

print('Tuning XGBoost: 40 trials...')
study_xgb = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=SEED))
study_xgb.optimize(xgb_obj, n_trials=40, show_progress_bar=True)
print(f'Best XGBoost F1: {study_xgb.best_value:.4f}')

Tuning XGBoost: 40 trials...

  0%|          | 0/40 [00:00<?, ?it/s]

Best XGBoost F1: 0.7486

In [15]:
# ── 14. Optuna: LightGBM ───────────────────────────────────────────────────
def lgbm_obj(trial):
    p = {
        'n_estimators':      trial.suggest_int('n_estimators', 300, 2500),
        'learning_rate':     trial.suggest_float('learning_rate', 0.005, 0.15, log=True),
        'num_leaves':        trial.suggest_int('num_leaves', 20, 400),
        'max_depth':         trial.suggest_int('max_depth', 3, 12),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
        'subsample':         trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree':  trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha':         trial.suggest_float('reg_alpha', 0.0, 3.0),
        'reg_lambda':        trial.suggest_float('reg_lambda', 0.5, 5.0),
        'class_weight': 'balanced', 'n_jobs': -1, 'random_state': SEED, 'verbose': -1,
    }
    sc = cross_val_score(lgb.LGBMClassifier(**p), X_train, y_train,
                          cv=StratifiedKFold(3,shuffle=True,random_state=SEED), scoring='f1', n_jobs=1)
    return sc.mean()

print('Tuning LightGBM: 40 trials...')
study_lgbm = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=SEED))
study_lgbm.optimize(lgbm_obj, n_trials=40, show_progress_bar=True)
print(f'Best LightGBM F1: {study_lgbm.best_value:.4f}')

Tuning LightGBM: 40 trials...

  0%|          | 0/40 [00:00<?, ?it/s]

Best LightGBM F1: 0.7449

In [16]:
# ── 15. Fit all tuned models ───────────────────────────────────────────────
cb_p   = {**study_cb.best_params,   'auto_class_weights': 'Balanced', 'verbose': 0, 'random_state': SEED}
xgb_p  = {**study_xgb.best_params,  'scale_pos_weight': scale_pos, 'eval_metric': 'logloss',
           'n_jobs': -1, 'random_state': SEED, 'verbosity': 0}
lgbm_p = {**study_lgbm.best_params, 'class_weight': 'balanced', 'n_jobs': -1,
           'random_state': SEED, 'verbose': -1}

tuned_cb   = CatBoostClassifier(**cb_p)
tuned_xgb  = XGBClassifier(**xgb_p)
tuned_lgbm = lgb.LGBMClassifier(**lgbm_p)
tuned_rf   = RandomForestClassifier(n_estimators=500, class_weight='balanced', n_jobs=-1, random_state=SEED)

print('Fitting tuned models...')
tuned_cb.fit(X_train, y_train)
tuned_xgb.fit(X_train, y_train)
tuned_lgbm.fit(X_train, y_train)
tuned_rf.fit(X_train_sm, y_train_sm)  # RF benefits from SMOTE
print('Done. Quick test accuracy:')
for name, m, Xte in [('CatBoost', tuned_cb, X_test), ('XGBoost', tuned_xgb, X_test),
                      ('LightGBM', tuned_lgbm, X_test), ('RF', tuned_rf, X_test)]:
    acc = accuracy_score(y_test, m.predict(Xte))
    mcc = matthews_corrcoef(y_test, m.predict(Xte))
    print(f'  {name:<12} Acc: {acc:.4f}  MCC: {mcc:.4f}')

Fitting tuned models...

Done. Quick test accuracy:
  CatBoost     Acc: 0.9598  MCC: 0.7427

  XGBoost      Acc: 0.9550  MCC: 0.7242

  LightGBM     Acc: 0.9528  MCC: 0.7132

  RF           Acc: 0.9643  MCC: 0.7668

In [17]:
# ── 16. Threshold optimization (per model) ─────────────────────────────────
# Default 0.5 threshold is suboptimal for 8.5% positive rate.
# Use a dedicated threshold-selection split (NOT the test set — that would be data leakage).

X_tr2, X_thr, y_tr2, y_thr = train_test_split(
    X_train, y_train, test_size=0.15, random_state=SEED, stratify=y_train
)

thresholds = {}
print(f'{"Model":<14} Opt-threshold  F1@thresh')
print('-'*45)
for name, model in [('CatBoost', tuned_cb), ('XGBoost', tuned_xgb),
                     ('LightGBM', tuned_lgbm), ('RF', tuned_rf)]:
    proba_thr = model.predict_proba(X_thr)[:,1]
    prec, rec, thrs = precision_recall_curve(y_thr, proba_thr)
    f1s = 2*prec*rec/(prec+rec+1e-9)
    best_idx = np.argmax(f1s[:-1])
    t = float(thrs[best_idx])
    thresholds[name] = t
    print(f'{name:<14} {t:.4f}         {f1s[best_idx]:.4f}')

Model          Opt-threshold  F1@thresh
---------------------------------------------
CatBoost       0.8978         0.9980
XGBoost        0.8470         0.9980

LightGBM       0.8016         0.9951
RF             0.4695         0.9970

In [18]:
# ── 17. Stacking Ensemble ──────────────────────────────────────────────────
estimators = [
    ('cb',   CatBoostClassifier(**cb_p)),
    ('xgb',  XGBClassifier(**xgb_p)),
    ('lgbm', lgb.LGBMClassifier(**lgbm_p)),
    ('rf',   RandomForestClassifier(n_estimators=500, class_weight='balanced', n_jobs=-1, random_state=SEED)),
]
stacker = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(C=1.0, class_weight='balanced', max_iter=1000, random_state=SEED),
    cv=5, stack_method='predict_proba', passthrough=True, n_jobs=-1,
)
print('Fitting stacking ensemble...')
stacker.fit(X_train, y_train)
stk_acc = accuracy_score(y_test, stacker.predict(X_test))
stk_mcc = matthews_corrcoef(y_test, stacker.predict(X_test))
print(f'Stacker — Acc: {stk_acc:.4f}  MCC: {stk_mcc:.4f}')

Fitting stacking ensemble...

Stacker — Acc: 0.9018  MCC: 0.6042

In [19]:
# ── 18. Full evaluation table ──────────────────────────────────────────────
rows = []
model_map = {'CatBoost': tuned_cb, 'XGBoost': tuned_xgb,
             'LightGBM': tuned_lgbm, 'RF': tuned_rf, 'Stacking': stacker}

for mname, model in model_map.items():
    # Default threshold 0.5
    rows.append(evaluate(model, X_test, y_test, f'{mname} t=0.5', 0.5))
    # Optimized threshold (not for stacker)
    if mname in thresholds:
        t = thresholds[mname]
        rows.append(evaluate(model, X_test, y_test, f'{mname} t={t:.3f}', t))

results_df = pd.DataFrame(rows)
print('=== FULL RESULTS TABLE (sorted by MCC — best metric for imbalanced data) ===')
display(results_df.sort_values('MCC', ascending=False).to_string(index=False))

print('\n=== WINNER BY EACH METRIC ===')
for m in ['Accuracy','Balanced_Acc','AUC_ROC','PR_AUC','F1','MCC','Recall_Sensitivity']:
    best = results_df.loc[results_df[m].idxmax()]
    print(f'{m:<22} {best["Model"]:<35} {best[m]:.4f}')

=== FULL RESULTS TABLE (sorted by MCC — best metric for imbalanced data) ===

'           Model  Threshold  Accuracy  Balanced_Acc  AUC_ROC  PR_AUC     F1  Precision  Recall_Sensitivity  Specificity    MCC  Kappa  Brier\nCatBoost t=0.898      0.898    0.9683        0.8482   0.9675  0.8574 0.7964     0.9197              0.7022       0.9941 0.7879 0.7796 0.0334\n XGBoost t=0.847      0.847    0.9673        0.8513   0.9685  0.8585 0.7930     0.8972              0.7105       0.9921 0.7818 0.7755 0.0352\nLightGBM t=0.802      0.802    0.9651        0.8565   0.9676  0.8575 0.7856     0.8576              0.7246       0.9884 0.7699 0.7667 0.0362\n        RF t=0.5      0.500    0.9641        0.8602   0.9683  0.8615 0.7830     0.8389              0.7341       0.9864 0.7656 0.7636 0.0291\n      RF t=0.469      0.469    0.9616        0.8618   0.9683  0.8615 0.7727     0.8077              0.7406       0.9829 0.7526 0.7517 0.0291\n  CatBoost t=0.5      0.500    0.9598        0.8602   0.9675  0.8574 0.7642     0.7907              0.7394       0.9811 0.7427 0.7422 0.0334\n   XGBoost t=0.5      0.500    0.9550        0.8670   0.9685  0.8585 0.7488     0.7378              0.7600       0.9739 0.7242 0.7241 0.0352\n  LightGBM t=0.5      0.500    0.9528        0.8642   0.9676  0.8575 0.7388     0.7220              0.7565       0.9718 0.7132 0.7129 0.0362\n  Stacking t=0.5      0.500    0.9018        0.8979   0.9736  0.8697 0.6160     0.4701              0.8933       0.9026 0.6042 0.5658 0.0673'

=== WINNER BY EACH METRIC ===
Accuracy               CatBoost t=0.898                    0.9683
Balanced_Acc           Stacking t=0.5                      0.8979
AUC_ROC                Stacking t=0.5                      0.9736
PR_AUC                 Stacking t=0.5                      0.8697
F1                     CatBoost t=0.898                    0.7964
MCC                    CatBoost t=0.898                    0.7879
Recall_Sensitivity     Stacking t=0.5                      0.8933

In [20]:
# ── 19. Overfitting check — learning curves ─────────────────────────────────
print('Computing learning curves (this takes a few minutes)...')
train_sizes, tr_sc, val_sc = learning_curve(
    CatBoostClassifier(**cb_p), X_train, y_train,
    cv=3, scoring='f1', n_jobs=-1,
    train_sizes=np.linspace(0.1,1.0,8), random_state=SEED
)

fig, ax = plt.subplots(figsize=(9,5))
ax.plot(train_sizes, tr_sc.mean(1), 'o-', color='#DA4167', label='Train F1')
ax.fill_between(train_sizes, tr_sc.mean(1)-tr_sc.std(1), tr_sc.mean(1)+tr_sc.std(1), alpha=0.15, color='#DA4167')
ax.plot(train_sizes, val_sc.mean(1), 'o-', color='#083D77', label='CV F1')
ax.fill_between(train_sizes, val_sc.mean(1)-val_sc.std(1), val_sc.mean(1)+val_sc.std(1), alpha=0.15, color='#083D77')
ax.set_xlabel('Training set size'); ax.set_ylabel('F1 Score')
ax.set_title('Learning Curves — CatBoost (Overfitting Check)', fontweight='bold')
ax.legend(); ax.grid(alpha=0.3)
gap = float(tr_sc.mean(1)[-1] - val_sc.mean(1)[-1])
ax.text(0.05, 0.1, f'Train-Val gap: {gap:.4f}  {"WARNING: overfitting" if gap>0.05 else "OK: no significant overfit"}',
        transform=ax.transAxes, fontsize=9, color='red' if gap>0.05 else 'green')
plt.tight_layout(); plt.savefig('learning_curves.png', dpi=100, bbox_inches='tight'); plt.close()
print(f'Train F1: {tr_sc.mean(1)[-1]:.4f}  CV F1: {val_sc.mean(1)[-1]:.4f}  Gap: {gap:.4f}')
print('Saved: learning_curves.png')

Computing learning curves (this takes a few minutes)...

Train F1: 0.9965  CV F1: 0.7560  Gap: 0.2405
Saved: learning_curves.png

In [21]:
# ── 20. Probability calibration ────────────────────────────────────────────
print('Calibrating probabilities (Platt scaling)...')
calibrated_cb = CalibratedClassifierCV(CatBoostClassifier(**cb_p), method='sigmoid', cv=5)
calibrated_cb.fit(X_train, y_train)

raw_brier = brier_score_loss(y_test, tuned_cb.predict_proba(X_test)[:,1])
cal_brier = brier_score_loss(y_test, calibrated_cb.predict_proba(X_test)[:,1])
print(f'Brier score — raw: {raw_brier:.4f}  calibrated: {cal_brier:.4f} (lower=better, 0=perfect)')
print('Use calibrated_cb for any application that needs trustworthy probability outputs.')

fig, axes = plt.subplots(1,2,figsize=(14,5))
for ax, (lbl, proba) in zip(axes, [
    ('CatBoost raw',        tuned_cb.predict_proba(X_test)[:,1]),
    ('CatBoost calibrated', calibrated_cb.predict_proba(X_test)[:,1])
]):
    fp, mp = calibration_curve(y_test, proba, n_bins=10)
    ax.plot(mp, fp, 'o-', color='#083D77', label=lbl)
    ax.plot([0,1],[0,1],'k--',alpha=0.5,label='Perfect')
    ax.set_xlabel('Mean predicted prob'); ax.set_ylabel('Fraction positives')
    ax.set_title(f'Calibration: {lbl}'); ax.legend(); ax.grid(alpha=0.3)
    brier = brier_score_loss(y_test, proba)
    ax.text(0.05, 0.9, f'Brier={brier:.4f}', transform=ax.transAxes, fontsize=9)
plt.tight_layout(); plt.savefig('calibration.png', dpi=100, bbox_inches='tight'); plt.close()
print('Saved: calibration.png')

Calibrating probabilities (Platt scaling)...

Brier score — raw: 0.0334  calibrated: 0.0285 (lower=better, 0=perfect)
Use calibrated_cb for any application that needs trustworthy probability outputs.

Saved: calibration.png

In [22]:
# ── 21. SHAP — model explainability ───────────────────────────────────────
print('Computing SHAP values (CatBoost, 2000 test samples)...')
try:
    explainer = shap.TreeExplainer(tuned_cb)
    shap_vals = explainer.shap_values(X_test.iloc[:2000])

    # Bar plot (mean absolute SHAP)
    fig, ax = plt.subplots(figsize=(9,7))
    shap.summary_plot(shap_vals, X_test.iloc[:2000], plot_type='bar', show=False, max_display=18)
    plt.title('SHAP Feature Importance (CatBoost)', fontweight='bold')
    plt.tight_layout(); plt.savefig('shap_importance.png', dpi=100, bbox_inches='tight'); plt.close()
    print('Saved: shap_importance.png')

    # Beeswarm (direction + magnitude)
    fig, ax = plt.subplots(figsize=(9,7))
    shap.summary_plot(shap_vals, X_test.iloc[:2000], plot_type='dot', show=False, max_display=18)
    plt.title('SHAP Beeswarm (CatBoost)', fontweight='bold')
    plt.tight_layout(); plt.savefig('shap_beeswarm.png', dpi=100, bbox_inches='tight'); plt.close()
    print('Saved: shap_beeswarm.png')

    # Print top features
    mean_abs_shap = np.abs(shap_vals).mean(0)
    shap_df = pd.DataFrame({'feature': X_test.columns, 'mean_|SHAP|': mean_abs_shap})
    shap_df = shap_df.sort_values('mean_|SHAP|', ascending=False)
    print('\nTop 10 features by mean |SHAP|:')
    print(shap_df.head(10).to_string(index=False))

except Exception as e:
    print(f'SHAP computation failed: {e}')
    print('Falling back to CatBoost built-in feature importance.')
    fi = pd.Series(tuned_cb.feature_importances_, index=X_train.columns).sort_values(ascending=False)
    print(fi.head(10).to_string())

Computing SHAP values (CatBoost, 2000 test samples)...

Saved: shap_importance.png

Saved: shap_beeswarm.png

Top 10 features by mean |SHAP|:
            feature  mean_|SHAP|
        HbA1c_level     3.671652
blood_glucose_level     2.584369
                age     2.034005
                bmi     1.010463
      dual_positive     0.813920
   glucose_diabetic     0.680287
    HbA1c_x_glucose     0.595126
    smoking_history     0.401027
  HbA1c_prediabetic     0.389638
       hypertension     0.242937

In [23]:
# ── 22. ROC + PR curves ────────────────────────────────────────────────────
fig, axes = plt.subplots(1,2,figsize=(16,6))
palette = ['#083D77','#DA4167','#F4D35E','#F78764','#22C55E']
for (name, model), color in zip(model_map.items(), palette):
    proba = model.predict_proba(X_test)[:,1]
    RocCurveDisplay.from_predictions(y_test, proba, name=name, ax=axes[0], color=color)
    PrecisionRecallDisplay.from_predictions(y_test, proba, name=name, ax=axes[1], color=color)
axes[0].plot([0,1],[0,1],'k--',alpha=0.3); axes[0].set_title('ROC Curves')
axes[1].set_title('Precision-Recall Curves (better metric for 8.5% positive rate)')
plt.tight_layout(); plt.savefig('roc_pr_curves.png', dpi=100, bbox_inches='tight'); plt.close()
print('Saved: roc_pr_curves.png')

Saved: roc_pr_curves.png

In [24]:
# ── 23. Confusion matrices ─────────────────────────────────────────────────
fig, axes = plt.subplots(1,5,figsize=(22,5))
fig.suptitle('Confusion Matrices (test set)', fontweight='bold')
for ax, (name, model) in zip(axes, model_map.items()):
    t = thresholds.get(name, 0.5)
    proba = model.predict_proba(X_test)[:,1]
    pred  = (proba >= t).astype(int)
    acc   = accuracy_score(y_test, pred)
    mcc   = matthews_corrcoef(y_test, pred)
    ConfusionMatrixDisplay(confusion_matrix(y_test, pred),
                           display_labels=['No DM','DM']).plot(ax=ax, colorbar=False, cmap='Blues')
    ax.set_title(f'{name}\nAcc {acc:.3f}  MCC {mcc:.3f}', fontsize=9)
plt.tight_layout(); plt.savefig('confusion_matrices.png', dpi=100, bbox_inches='tight'); plt.close()
print('Saved: confusion_matrices.png')

# Best model full report
best_name = results_df.sort_values('MCC',ascending=False).iloc[0]['Model']
bm_key    = best_name.split(' t=')[0]  # strip threshold suffix safely
bm        = model_map.get(bm_key, tuned_cb)
bm_t      = thresholds.get(bm_key, 0.5)
print(f'\nBest model: {best_name}')
print(classification_report(
    y_test, (bm.predict_proba(X_test)[:,1] >= bm_t).astype(int),
    target_names=['No Diabetes','Diabetes']
))

Saved: confusion_matrices.png

Best model: CatBoost t=0.898
              precision    recall  f1-score   support

 No Diabetes       0.97      0.99      0.98     17534
    Diabetes       0.92      0.70      0.80      1696

    accuracy                           0.97     19230
   macro avg       0.95      0.85      0.89     19230
weighted avg       0.97      0.97      0.97     19230

In [25]:
# ── 24. PIMA benchmark ─────────────────────────────────────────────────────
print('=== PIMA Indians Benchmark (768 rows) ===')
Xp, yp = df_p.drop(columns=['Outcome']), df_p['Outcome']
Xp_tr,Xp_te,yp_tr,yp_te = train_test_split(Xp,yp,test_size=0.2,random_state=SEED,stratify=yp)
sc_p = RobustScaler()
Xp_tr_sc = pd.DataFrame(sc_p.fit_transform(Xp_tr), columns=Xp.columns)
Xp_te_sc  = pd.DataFrame(sc_p.transform(Xp_te),    columns=Xp.columns)
sp_p = float((yp_tr==0).sum()/(yp_tr==1).sum())

cv_p = StratifiedKFold(5,shuffle=True,random_state=SEED)
for name, model in [('CatBoost',  CatBoostClassifier(iterations=1500,learning_rate=0.03,depth=6,auto_class_weights='Balanced',verbose=0,random_state=SEED)),
                     ('XGBoost',   XGBClassifier(n_estimators=500,learning_rate=0.05,max_depth=5,scale_pos_weight=sp_p,eval_metric='logloss',n_jobs=-1,random_state=SEED,verbosity=0)),
                     ('LightGBM',  lgb.LGBMClassifier(n_estimators=500,class_weight='balanced',n_jobs=-1,random_state=SEED,verbose=-1))]:
    acc = cross_val_score(model,Xp_tr_sc,yp_tr,cv=cv_p,scoring='accuracy',n_jobs=-1)
    f1  = cross_val_score(model,Xp_tr_sc,yp_tr,cv=cv_p,scoring='f1',      n_jobs=-1)
    mcc = cross_val_score(model,Xp_tr_sc,yp_tr,cv=cv_p,scoring='matthews_corrcoef',n_jobs=-1)
    print(f'{name:<12} Acc:{acc.mean():.4f} F1:{f1.mean():.4f} MCC:{mcc.mean():.4f}')

print('\nNote: 80-85% accuracy is top-tier for PIMA. Small dataset (768 rows) = true ceiling.')

=== PIMA Indians Benchmark (768 rows) ===

CatBoost     Acc:0.7345 F1:0.6229 MCC:0.4204

XGBoost      Acc:0.7361 F1:0.6270 MCC:0.4247

LightGBM     Acc:0.7361 F1:0.6036 MCC:0.4099

Note: 80-85% accuracy is top-tier for PIMA. Small dataset (768 rows) = true ceiling.

In [26]:
# ── 25. Save everything ────────────────────────────────────────────────────
artifacts = {
    'catboost_tuned':     tuned_cb,
    'catboost_calibrated':calibrated_cb,
    'xgboost_tuned':      tuned_xgb,
    'lgbm_tuned':         tuned_lgbm,
    'rf_tuned':           tuned_rf,
    'stacker':            stacker,
    'scaler':             scaler,
    'knn_imputer_pima':   knn_imp,
    'label_encoders':     le_map,
    'feature_cols':       list(X_train.columns),
    'optimal_thresholds': thresholds,
    'scale_pos_weight':   scale_pos,
}
for name, obj in artifacts.items():
    with open(os.path.join(SAVE_DIR, f'{name}.pkl'), 'wb') as f:
        pickle.dump(obj, f)
results_df.sort_values('MCC',ascending=False).to_csv('model_results.csv', index=False)
print('Saved all artifacts + model_results.csv')
for k in artifacts: print(f'  {k}.pkl')

Saved all artifacts + model_results.csv
  catboost_tuned.pkl
  catboost_calibrated.pkl
  xgboost_tuned.pkl
  lgbm_tuned.pkl
  rf_tuned.pkl
  stacker.pkl
  scaler.pkl
  knn_imputer_pima.pkl
  label_encoders.pkl
  feature_cols.pkl
  optimal_thresholds.pkl
  scale_pos_weight.pkl

In [27]:
# ── 26. Final Summary ──────────────────────────────────────────────────────
print('='*64)
print('GLUCOSENSE OBLITERATOR v1 — FINAL RESULTS')
print('='*64)
display(results_df.sort_values('MCC',ascending=False)[['Model','Accuracy','AUC_ROC','PR_AUC','F1','MCC','Balanced_Acc','Brier']].to_string(index=False))
print()
print('CONSTRAINTS COVERED:')
checks = [
    'Duplicate rows dropped',
    'PIMA impossible zeros → KNN imputed',
    'Outlier capping (HbA1c>14, glucose>600, BMI>70)',
    'Index/ID leak columns dropped',
    'Binary features from RAW data (FIXED: not from scaled)',
    'Scaler fit ONLY on train — never on test',
    'Class imbalance: class_weight=balanced + SMOTE',
    'Stratified 5-fold CV on all models',
    'Optuna tunes F1 (not accuracy — imbalanced data)',
    'Threshold optimized per model (not fixed 0.5)',
    'Stacking ensemble (CB+XGB+LGBM+RF+LR)',
    'Overfitting check via learning curves + train/val gap',
    'Probability calibration (Brier score reported)',
    'SHAP feature importance + direction',
    'PR-AUC (correct metric for imbalanced data)',
    'MCC (most robust metric for imbalanced binary classification)',
    'Specificity + Balanced Accuracy + Kappa',
    'McFadden pseudo-R² for LR (R²/Adj-R² = regression only, NOT used here)',
    'Target leakage disclosed (HbA1c+glucose = diagnostic criteria)',
]
for c in checks: print(f'  [x] {c}')
print()
print('NEXT: Antenna regression notebook → there R² and Adjusted R² WILL apply.')

================================================================
GLUCOSENSE OBLITERATOR v1 — FINAL RESULTS
================================================================

'           Model  Accuracy  AUC_ROC  PR_AUC     F1    MCC  Balanced_Acc  Brier\nCatBoost t=0.898    0.9683   0.9675  0.8574 0.7964 0.7879        0.8482 0.0334\n XGBoost t=0.847    0.9673   0.9685  0.8585 0.7930 0.7818        0.8513 0.0352\nLightGBM t=0.802    0.9651   0.9676  0.8575 0.7856 0.7699        0.8565 0.0362\n        RF t=0.5    0.9641   0.9683  0.8615 0.7830 0.7656        0.8602 0.0291\n      RF t=0.469    0.9616   0.9683  0.8615 0.7727 0.7526        0.8618 0.0291\n  CatBoost t=0.5    0.9598   0.9675  0.8574 0.7642 0.7427        0.8602 0.0334\n   XGBoost t=0.5    0.9550   0.9685  0.8585 0.7488 0.7242        0.8670 0.0352\n  LightGBM t=0.5    0.9528   0.9676  0.8575 0.7388 0.7132        0.8642 0.0362\n  Stacking t=0.5    0.9018   0.9736  0.8697 0.6160 0.6042        0.8979 0.0673'

CONSTRAINTS COVERED:
  [x] Duplicate rows dropped
  [x] PIMA impossible zeros → KNN imputed
  [x] Outlier capping (HbA1c>14, glucose>600, BMI>70)
  [x] Index/ID leak columns dropped
  [x] Binary features from RAW data (FIXED: not from scaled)
  [x] Scaler fit ONLY on train — never on test
  [x] Class imbalance: class_weight=balanced + SMOTE
  [x] Stratified 5-fold CV on all models
  [x] Optuna tunes F1 (not accuracy — imbalanced data)
  [x] Threshold optimized per model (not fixed 0.5)
  [x] Stacking ensemble (CB+XGB+LGBM+RF+LR)
  [x] Overfitting check via learning curves + train/val gap
  [x] Probability calibration (Brier score reported)
  [x] SHAP feature importance + direction
  [x] PR-AUC (correct metric for imbalanced data)
  [x] MCC (most robust metric for imbalanced binary classification)
  [x] Specificity + Balanced Accuracy + Kappa
  [x] McFadden pseudo-R² for LR (R²/Adj-R² = regression only, NOT used here)
  [x] Target leakage disclosed (HbA1c+glucose = diagnostic criteria)

NEXT: Antenna regression notebook → there R² and Adjusted R² WILL apply.